### ISSUE TITLE
文章隐藏

### ISSUE THREAD

**Issue by myronzhangweb3** [auroral-ui/hexo-plugin-aurora#9]
有一个需求场景，在页面展示一个目录，目录指向多个博客页面。

之前我的做法是把目录博客页展示，但把每一章节的博客hidden:true，但是现在这个框架无法展示hidden为true的文章，因为hidden为true的不再被解析，api接口返回找不到文章。

或者是否有其他方案？

**Comment by Sang-Buster** [comment]
同意，很需要这个哈 😁

**Comment by bennyxguo** [comment]
没有明白这个需求。你是想把 `hidden:true` 的文章也显示出来？在哪里显示？

**Comment by myronzhangweb3** [comment]
> 没有明白这个需求。你是想把 `hidden:true` 的文章也显示出来？在哪里显示？

不展示在文章列表   但可以使用url访问即可  我使用别的框架的用法：https://zhangzhishun.github.io/2022/07/01/blockchain/ethereum/source_question/%E4%BB%A5%E5%A4%AA%E5%9D%8A%E6%A0%B8%E5%BF%83%E9%97%AE%E9%A2%98/

这里所有文章都是hidden：true的

**Comment by Sang-Buster** [comment]
我是想把page放到feature文章，这样更显眼， 而不是只放在导航栏。目前的做法是写feature post, 如果有隐藏文章选项，就可以达到相同目的了。

主要是有些blog拿来做一系列教学/教程， 如果要写一章节里面很多小节的post，有个chapter index post就行了 这样主页的文章排版看起来也会比较干净。

**Comment by bennyxguo** [comment]
> 我是想把page放到feature文章，这样更显眼， 而不是只放在导航栏。目前的做法是写feature post, 如果有隐藏文章选项，就可以达到相同目的了。
> 
> 
> 
> 主要是有些blog拿来做一系列教学/教程， 如果要写一章节里面很多小节的post，有个chapter index post就行了 这样主页的文章排版看起来也会比较干净。

那直接把有 hidden 的从首页列表移除就行了。

**Comment by Sang-Buster** [comment]
> 那直接把有 hidden 的从首页列表移除就行了。

对的， 给 feature post加个hidden：true 让它不显示在文章列表里。目前应该还没有这个功能吧？还是我漏看啥了😦

**Comment by myronzhangweb3** [comment]
非常棒👍👍👍

**Comment by myronzhangweb3** [comment]
能否在“上一篇更回味”和“下一篇更精彩”也隐藏一下呢？
